services:
    gateway:
        build:
            context: src/gateway
        command: ["--listen", ":8080", "--to", ":8081"]
        ports:
            - "8080:8080"

    users:
        build:
            context: src/users
        command: ["--port", "8080"]
        ports:
            - "8081:8080"
        depends_on:
            - gateway
            - postgres_users

    postgres_users:
        image: postgres:latest
        container_name: postgres_users_container
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: users
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
        command: >
            postgres -c max_connections=1000
                     -c shared_buffers=256MB
                     -c effective_cache_size=768MB
                     -c maintenance_work_mem=64MB
                     -c checkpoint_completion_target=0.7
                     -c wal_buffers=16MB
                     -c default_statistics_target=100
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U user -d users" ]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        tty: true
        stdin_open: true

volumes:
    pgdata:
        driver: local
