services:
    gateway:
        build:
            context: src/gateway
        command: ["--from", "8080", "--to", "8081"]
        ports:
            - "8080:8080"

    users:
        build:
            context: src/users
        command: ["--port", "8080"]
        ports:
            - "8081:8080"
        depends_on:
            - gateway
