/*
 * Social Network
 *
 * This is a homework project for Service-Oriented Architectures cource
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

type InlineResponse400 struct {
	IncorrectField string `json:"incorrectField,omitempty"`

	ErrorMessage string `json:"errorMessage,omitempty"`
}
