/*
 * Social Network
 *
 * This is a homework project for Service-Oriented Architectures cource
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProfileField struct {
	FieldName string `json:"fieldName,omitempty"`

	FieldValue string `json:"fieldValue,omitempty"`
}
