/*
 * Social Network
 *
 * This is a homework project for Service-Oriented Architectures cource
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"LoginGet",
		strings.ToUpper("Get"),
		"/login",
		LoginGet,
	},

	Route{
		"UsersGet",
		strings.ToUpper("Get"),
		"/users",
		UsersGet,
	},

	Route{
		"UsersPatch",
		strings.ToUpper("Patch"),
		"/users",
		UsersPatch,
	},

	Route{
		"UsersPost",
		strings.ToUpper("Post"),
		"/users",
		UsersPost,
	},

	Route{
		"Token",
		strings.ToUpper("Get"),
		"/token",
		TokenGet,
	},
}
