@startuml

' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "LoginOptions" #Application {
  possible_login : text (username or email or phone)
  --
  user_id : uint
}

entity "UserCredentials" #Application {
  user_id : uint <<generated>>
  --
  username : text
  password_hash : byte[256]
  email: text
  phone: text (normalized)
}

entity "UserProfile" #Application {
  user_id : uint
  --
  profile_picture : link
  bio : text
  last_online : timestamp
  created : timestamp
  admin_level : enum {user, moderator, admin}
}

entity "Post" #Business {
  post_id : uint
  --
  user_id : uint
  content : text
  created : timestamp
  last_edited : timestamp
  attachment_id : uint or NULL
}

entity "Comment" #Business {
  comment_id : uint
  --
  post_id : uint
  reply_to_comment: uint or NULL
  content: text
  author_id : uint
  created : timestamp
  last_edited : timestamp
}

entity "Attachment" #Business {
  attachment_id : uint
  --
  link : text
  created : timestamp
  last_edited : timestamp
  type : enum {image, file}
}

entity "ViewEvent" #Strategy {
  post_id : uint
  --
  user_id : uint
  time : timestamp
  view_duration : float
  reaction : enum {none, like, dislike}
}

entity "PostStats" #Strategy {
  post_id : uint
  --
  views : uint
  likes : uint
  dislikes : uint
  avg_retention : float
}

entity "UserStats" #Strategy {
  user_id : uint
  --
  views : uint
  likes : uint
  dislikes : uint
  avg_retention : float
}

UserCredentials ||--|{ LoginOptions : "user_id"
UserCredentials ||--|| UserProfile : "user_id"
UserProfile ||--o{ Post : "user_id"
Post ||--o{ Comment : "post_id"
Comment ||--o{ Comment
Post ||--o| Attachment
Post ||--{ ViewEvent : "post_id"
Post ||--|| PostStats : "post_id"
ViewEvent }o--|| PostStats : "post_id"
ViewEvent }o--|| UserStats : "user_id"
UserProfile ||--|| UserStats : "user_id"

@enduml
