name: Deploy API Docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate API docs and deploy to GitHub Pages
        uses: msayson/openapi-github-pages-action@v2.0.0
        with:
          api-configs: |
            [
              {
                "branch": "main",
                "openapi-json-filepath": "docs/openapi.json",
                "api-doc-filepath": "api-docs"
              }
            ]
          api-docs-dir: 'docs'
