name: Go test

on:
  push:
    branches:
      - main
      - hw6

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.test.yml
          service: tests
          registry: docker.io
